version: "3.6"

services:
  db:
    image: "mariadb:11.2"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mesabos_root_pwd
      MARIADB_USER: mesabos_usr
      MARIADB_PASSWORD: mesabos_pwd
      MARIADB_DATABASE: mesabos
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb_data: